SELECT
  PK.COD_CAT AS Categoria,
  PK.COD_CAL AS Calibre,
  CASE
    WHEN CHARINDEX('D.', PK.COD_CAL) > 0 THEN 'Dark Dark'
    WHEN CHARINDEX('D', PK.COD_CAL) > 0 THEN 'Dark'
    ELSE 'Light'
  END AS Color,
  PK.NRO_MIX AS NroMix,
  PK.LOTE AS Pallet,
  PK.CAJAS AS Cajas,
  (A.KILOS * PK.CAJAS) AS Kilos,
  PK.PLANILLA AS Proceso,
  V.NOM_VAR AS Variedad,
  E.NOM_ESP AS Especie,
  p1.NOM_PACK AS Packing,
  PK.COD_ETI AS Etiqueta,
  PK.TIPO_LOT AS TipoPallet,
  PK.ALTURA AS Altura,
  PK.FECHA_PAC AS FechaPacking,
  P.NOM_PRO AS Productor,
  PRE.COD_PRE AS CSG,
  C.DESCRIPCION AS Comuna,
  PK.COD_ENV AS Envase,
  PK.COD_ENVOP AS Embalaje,
  bp.DESCRIPCION AS BasePallet
FROM
  Erpfrusys.dbo.PROPACKLOTE AS PK
  JOIN Erpfrusys.dbo.PRODUCTORES AS P ON PK.COD_PRO_ETIQUETADO = P.COD_PRO
  AND PK.COD_TEM = P.COD_TEM
  AND PK.COD_EMP = P.COD_EMP
  JOIN Erpfrusys.dbo.ESPECIE AS E ON PK.COD_ESP = E.COD_ESP
  AND PK.COD_TEM = E.COD_TEM
  AND PK.COD_EMP = E.COD_EMP
  JOIN Erpfrusys.dbo.VARIEDAD AS V ON PK.COD_VAR = V.COD_VAR
  AND E.COD_ESP = V.COD_ESP
  AND PK.COD_TEM = V.COD_TEM
  AND PK.COD_EMP = V.COD_EMP
  JOIN Erpfrusys.dbo.BASE_PLT AS bp ON PK.COD_TEM = BP.COD_TEM
  AND PK.COD_EMP = BP.COD_EMP
  AND PK.COD_BP = bp.COD_BP
  JOIN Erpfrusys.dbo.PACKINGS AS p1 ON PK.COD_PACK = p1.COD_PACK
  AND PK.COD_TEM = p1.COD_TEM
  AND PK.COD_EMP = p1.COD_EMP
  JOIN Erpfrusys.dbo.AJUSTE AS a ON PK.COD_TEM = a.COD_TEM
  AND PK.COD_EMP = a.COD_EMP
  AND PK.PLANILLA = a.PLANILLA
  AND PK.COD_ENVOP = a.COD_ENVOP
  JOIN Erpfrusys.dbo.PREDIOS AS pre ON PK.COD_EMP = pre.COD_EMP
  AND PK.COD_PRO = pre.COD_PRO
  AND PK.COD_TEM = pre.COD_TEM
  AND PK.COD_PRE = pre.COD_PRE
  JOIN Erpfrusys.dbo.COMUNAS AS c ON PK.COD_EMP = c.COD_EMP
  AND PK.COD_TEM = c.COD_TEM
  AND pre.COD_EMP = c.COD_EMP
  AND pre.COD_TEM = c.COD_TEM
  AND pre.COD_COM = c.COD_COM
WHERE
  PK.COD_TEM = 7
  AND PK.COD_EMP = 'MER'
  AND PK.ZON = 'C'
  AND NRO_MIX = 0
  AND PK.COD_PRO LIKE 'HU%'
  AND PK.COD_ESP = 5
  AND PK.FECHA_RPA > '01/12/2023'
UNION
ALL
SELECT
  PK.COD_CAT AS Categoria,
  PK.COD_CAL AS Calibre,
  CASE
    WHEN CHARINDEX('D.', PK.COD_CAL) > 0 THEN 'Dark Dark'
    ELSE 'No es dark dark'
  END AS Color,
  PK.NRO_MIX AS NroMix,
  PK.LOTE AS Pallet,
  PK.CAJAS AS Cajas,
  (A.KILOS * PK.CAJAS) AS Kilos,
  PK.PLANILLA AS Proceso,
  V.NOM_VAR AS Variedad,
  E.NOM_ESP AS Especie,
  p1.NOM_PACK AS Packing,
  PK.COD_ETI AS Etiqueta,
  PK.TIPO_LOT AS TipoPallet,
  PK.ALTURA AS Altura,
  PK.FECHA_PAC AS FechaPacking,
  P.NOM_PRO AS Productor,
  PRE.COD_PRE AS CSG,
  C.DESCRIPCION AS Comuna,
  PK.COD_ENV AS Envase,
  PK.COD_ENVOP AS Embalaje,
  BP.DESCRIPCION AS BasePallet
FROM
  Erpfrusys.dbo.PROPACKMIX AS PK
  JOIN Erpfrusys.dbo.PRODUCTORES AS P ON PK.COD_PRO_ETIQUETADO = P.COD_PRO
  AND PK.COD_TEM = P.COD_TEM
  AND PK.COD_EMP = P.COD_EMP
  JOIN Erpfrusys.dbo.TIT_PROCEPACK AS TP ON TP.COD_EMP = PK.COD_EMP
  AND TP.COD_TEM = PK.COD_TEM
  AND TP.ZON = PK.ZON
  AND TP.PLANILLA = PK.PROCESO
  AND TP.COD_PRO = PK.COD_PRO
  JOIN Erpfrusys.dbo.ESPECIE AS E ON PK.COD_ESP = E.COD_ESP
  AND PK.COD_TEM = E.COD_TEM
  AND PK.COD_EMP = E.COD_EMP
  JOIN Erpfrusys.dbo.VARIEDAD AS V ON PK.COD_VAR = V.COD_VAR
  AND E.COD_ESP = V.COD_ESP
  AND PK.COD_TEM = V.COD_TEM
  AND PK.COD_EMP = V.COD_EMP
  JOIN Erpfrusys.dbo.BASE_PLT AS bp ON PK.COD_TEM = BP.COD_TEM
  AND PK.COD_EMP = BP.COD_EMP
  AND PK.COD_BP = bp.COD_BP
  JOIN Erpfrusys.dbo.PACKINGS AS p1 ON PK.COD_PACK = p1.COD_PACK
  AND PK.COD_TEM = p1.COD_TEM
  AND PK.COD_EMP = p1.COD_EMP
  JOIN Erpfrusys.dbo.AJUSTE AS a ON PK.COD_TEM = a.COD_TEM
  AND PK.COD_EMP = a.COD_EMP
  AND PK.PLANILLA = a.PLANILLA
  AND PK.COD_ENVOP = a.COD_ENVOP
  JOIN Erpfrusys.dbo.PREDIOS AS pre ON PK.COD_EMP = pre.COD_EMP
  AND PK.COD_PRO = pre.COD_PRO
  AND PK.COD_TEM = pre.COD_TEM
  AND PK.COD_PRE = pre.COD_PRE
  JOIN Erpfrusys.dbo.COMUNAS AS c ON PK.COD_EMP = c.COD_EMP
  AND PK.COD_TEM = c.COD_TEM
  AND pre.COD_EMP = c.COD_EMP
  AND pre.COD_TEM = c.COD_TEM
  AND pre.COD_COM = c.COD_COM
WHERE
  PK.COD_TEM = 7
  AND PK.COD_EMP = 'MER'
  AND PK.ZON = 'C'
  AND PK.COD_PRO LIKE 'HU%'
  AND PK.COD_ESP = 5
  AND PK.FECHA_RPA > '01/12/2023';