SELECT
  t.T_PROCESO AS 'TIPO PROCESO',
  P1.COD_ESP AS 'ESPECIE',
  SUM(TOTAL_KILOS) AS 'TOTAL KILOS'
FROM
  [ERPFRUSYS].DBO.PROCEPACK AS P1
  JOIN [ERPFRUSYS].DBO.TIT_PROCEPACK AS T ON P1.ZON = T.ZON
  AND P1.PLANILLA = T.PLANILLA
  AND P1.COD_EMP = T.COD_EMP
  AND P1.COD_TEM = T.COD_TEM
WHERE
  P1.TIPOFRU_PK = 'E'
  AND p1.COD_TEM = 6
  AND t.FECHA_RPA BETWEEN '01-07-2023 0:00:00' AND '31-07-2023 23:59:00'
GROUP BY
  T.T_PROCESO,
  P1.COD_ESP
UNION
ALL
SELECT
  Cod_Tip_Proceso AS 'TIPO PROCESO',
  cod_Especie AS 'ESPECIE',
  sum(KilosEntrada) AS 'TOTAL KILOS'
FROM
  [192.168.1.79].[teno].[dbo].[procesos_nuez]
WHERE
  Fecha_Proc BETWEEN '01-07-2023 0:00:00' AND '31-07-2023 23:59:59'
GROUP BY
  Cod_Tip_Proceso,
  cod_Especie;