SELECT
  P.COD_PRE AS CSG,
  C.DESCRIPCION AS COMUNA,
  P.COD_PRO,
  P.COD_TEM,
  P.DESCRIPCION,
  P.DIRECCION,
  P.REGION,
  PRO.DESCRIPCION AS PROVINCIA,
  P.COD_EMP
FROM
  Erpfrusys.dbo.COMUNAS AS C
  JOIN Erpfrusys.dbo.PREDIOS AS P ON C.COD_COM = P.COD_COM
  JOIN Erpfrusys.dbo.PROVINCIAS AS PRO ON PRO.COD_EMP = P.COD_EMP
  AND PRO.COD_TEM = P.COD_TEM
  AND P.COD_PROVC = PRO.COD_PROVC
WHERE
  (P.COD_TEM = '5')
  AND (P.COD_EMP = 'MER')
  AND (P.REGION IS NOT NULL);