SELECT
  E.LOTE AS FOLIO,
  E.COD_PRO,
  P.NOM_PRO,
  E.COD_EMP,
  E.COD_TEM,
  E.COD_ESP,
  ESP.NOM_ESP,
  E.COD_VAR,
  [VAR].NOM_VAR,
  PXE.COD_EXP,
  EXP.NOM_EXP,
  E.CANTIDAD,
  E.TOTAL_KILOS
FROM
  Erpfrusys.dbo.EXISPACK AS E
  LEFT JOIN Erpfrusys.dbo.EXISPACK_DET AS ED ON E.LOTE = ED.LOTE
  AND E.COD_TEM = ED.COD_TEM
  AND E.COD_EMP = ED.COD_EMP
  LEFT JOIN Erpfrusys.dbo.PRODUCTORES AS P ON E.COD_PRO = P.COD_PRO
  AND E.COD_TEM = P.COD_TEM
  AND E.COD_EMP = P.COD_EMP
  LEFT JOIN Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR AS PXE ON E.COD_PRO = PXE.COD_PRO
  AND E.COD_TEM = PXE.COD_TEM
  AND E.COD_EMP = PXE.COD_EMP
  LEFT JOIN Erpfrusys.dbo.EXPORTADORES AS EXP ON PXE.COD_EXP = EXP.COD_EXP
  AND PXE.COD_TEM = EXP.COD_TEM
  AND PXE.COD_EMP = EXP.COD_EMP
  LEFT JOIN Erpfrusys.dbo.ESPECIE AS ESP ON E.COD_ESP = ESP.COD_ESP
  AND E.COD_TEM = ESP.COD_TEM
  AND E.COD_EMP = ESP.COD_EMP
  LEFT JOIN Erpfrusys.dbo.VARIEDAD AS [VAR] ON E.COD_VAR = [VAR].COD_VAR
  AND E.COD_TEM = [VAR].COD_TEM
  AND E.COD_EMP = [VAR].COD_EMP;