SELECT
  a.[Tipo Frio],
  a.Empresa,
  a.Temporada,
  a.[Nº Guia de Recepcion],
  a.FechaRecepcion,
  a.[Fecha Cosecha],
  a.Zona,
  a.CodigoPacking,
  a.CodigoProductor,
  a.CodigoFrio,
  a.CodigoEspecie,
  a.CodigoVariedad,
  a.NumeroLote,
  a.CodigoEnvase,
  a.CANTIDAD,
  a.KilosPromedio,
  a.TotalKilos,
  a.NombreTemporada,
  a.NombreEmpresa,
  a.NombreProductor,
  a.NombreFrio,
  a.NombrePacking,
  a.NombreEspecie,
  a.NombreVariedad,
  a.NombreZona,
  a.TipoFruta,
  a.[Guía de Recepción Productor (SII)],
  a.[Calidad Packing],
  a.[Nombre Grupo Productores],
  a.[Codigo Grupo Productores],
  a.[Nombre Conductor],
  a.PATENTE,
  a.[Hora Recepcion],
  a.[Codigo Grupo Huerto],
  a.[Nombre Grupo Huerto],
  a.[Codigo Predio],
  a.[Nombre Predio],
  a.[Codigo Cuartel],
  a.[Nombre Cuartel],
  a.[Asignado a Cta.Cte. Envases],
  a.Observaciones,
  a.[Codigo Tipo Tratamiento],
  a.[Tipo Tratamiento],
  a.[Tipo Recepcion],
  a.[Estatus Recepcion],
  a.[Cod Exportadora],
  a.[Nom Exportadora],
  a.[Codigo Grado Madurez],
  a.[Grado Madurez],
  C.fec_ini AS [Inicio Desverdizado],
  C.fec_fin AS [Inicio Ventilado],
  C.fec_ven AS [Fin Ventilado],
  d.cod_cal AS calibre,
  C.id
FROM
  Erpfrusys.dbo.viewConsultaRecepcionPackingExcel AS a
  LEFT JOIN dbo.pk_desver_det AS d ON a.NumeroLote = d.folio
  LEFT JOIN dbo.pk_desver_cab AS C ON d.id_cab = C.id
WHERE
  (a.Empresa = 'MER')
  AND (a.Temporada = '7');