SELECT
  TOP (100) PERCENT B.PLANILLA AS PLANILLA_CALIDAD,
  B.COD_PRES_SOL,
  P.DESCRIPCION,
  CASE
    WHEN B.SOLIDOS_SOLUBLES = 1 THEN 'BRIX'
    ELSE 'FIRMEZA'
  END AS TIPO,
  B.VALOR
FROM
  Erpfrusys.dbo.CTRL_PRES_SOLIDOS AS B
  LEFT JOIN Erpfrusys.dbo.CTRL_PRESIONES AS P ON B.COD_PRES_SOL = P.COD_PRES_SOL
  AND B.COD_EMP = P.COD_EMP
  AND B.COD_TEM = P.COD_TEM
WHERE
  (B.COD_TEM = '7')
  AND (B.COD_PRES_SOL IS NOT NULL)
  AND B.VALOR <> '0'
ORDER BY
  PLANILLA_CALIDAD;