SELECT
  B.PLANILLA AS PLANILLA_CALIDAD,
  B.COD_PRES_SOL,
  P.DESCRIPCION,
  CASE
    WHEN B.SOLIDOS_SOLUBLES = 1
    AND (
      P.DESCRIPCION IS NULL
      OR P.DESCRIPCION = 'BRIX'
    ) THEN 'BRIX'
    WHEN B.ALMIDON = 1
    AND (
      P.DESCRIPCION IS NULL
      OR P.DESCRIPCION = 'ALMIDON'
    ) THEN 'ALMIDON'
    WHEN B.PROMEDIO = 1
    AND P.DESCRIPCION IS NULL
    AND B.SOLIDOS_SOLUBLES <> 1
    AND B.ALMIDON <> 1 THEN 'PROMEDIO'
    WHEN B.COD_PRES_SOL IS NOT NULL THEN 'FIRMEZA'
    ELSE 'SIN DEFINIR'
  END AS TIPO,
  B.VALOR
FROM
  Erpfrusys.dbo.CTRL_PRES_SOLIDOS AS B
  LEFT JOIN Erpfrusys.dbo.CTRL_PRESIONES AS P ON B.COD_PRES_SOL = P.COD_PRES_SOL
  AND B.COD_EMP = P.COD_EMP
  AND B.COD_TEM = P.COD_TEM
WHERE
  (B.COD_TEM = '7')
  AND B.VALOR <> 0
  AND B.PROMEDIO <> 1;