SELECT
  P.PLANILLA AS proceso,
  P.FECHA_RPA AS fecha,
  ISNULL(L.COD_LINEA, P.COD_LINEA) AS cod_linea,
  ISNULL(PRO.COD_PRO, P.COD_PRO) AS cod_pro,
  PRO.NOM_PRO,
  ISNULL(ESP.COD_ESP, P.COD_ESP) AS cod_esp,
  ESP.NOM_ESP,
  ISNULL([VAR].COD_VAR, P.COD_VAR) AS cod_var,
  [VAR].NOM_VAR,
  P.COD_EMP,
  P.COD_TEM,
  L.NOM_LINEA
FROM
  Erpfrusys.dbo.TIT_PROCEPACK AS P
  LEFT JOIN Erpfrusys.dbo.PRODUCTORES AS PRO ON P.COD_PRO = PRO.COD_PRO
  AND P.COD_EMP = PRO.COD_EMP
  AND P.COD_TEM = PRO.COD_TEM
  LEFT JOIN Erpfrusys.dbo.ESPECIE AS ESP ON P.COD_ESP = ESP.COD_ESP
  AND P.COD_EMP = ESP.COD_EMP
  AND P.COD_TEM = ESP.COD_TEM
  LEFT JOIN Erpfrusys.dbo.VARIEDAD AS [VAR] ON P.COD_VAR = [VAR].COD_VAR
  AND P.COD_EMP = [VAR].COD_EMP
  AND P.COD_TEM = [VAR].COD_TEM
  LEFT JOIN Erpfrusys.dbo.TIPOLINEAPK AS L ON P.COD_LINEA = L.COD_LINEA
  AND P.COD_EMP = L.COD_EMP
  AND P.COD_TEM = L.COD_TEM
WHERE
  (P.COD_TEM = 5)
  AND (P.COD_EMP = 'MER');