SELECT
  CTRL_DATOS.PLANILLA,
  ci.DESCRIPCION,
  CTRL_DATOS.DESCRIPCION AS 'UNIDAD',
  ci.ITEM
FROM
  Erpfrusys.dbo.CTRL_DATOS
  LEFT JOIN Erpfrusys.dbo.CTRL_ITEM AS ci ON CTRL_DATOS.COD_TEM = ci.COD_TEM
  AND CTRL_DATOS.COD_EMP = ci.COD_EMP
  AND CTRL_DATOS.TIPO = ci.TIPO
  AND CTRL_DATOS.COD_ITEM = ci.COD_ITEM
  AND CTRL_DATOS.COD_FAMILIA = ci.COD_FAMILIA
WHERE
  CTRL_DATOS.COD_TEM = 7
  AND ci.ITEM = '2';