SELECT
  EXPORTADORES.COD_EXP,
  EXPORTADORES.COD_TEM,
  EXPORTADORES.COD_EMP,
  EXPORTADORES.NOM_EXP,
  EXPORTADORAS.COD_PRO,
  EXPORTADORAS.TIP_COM
FROM
  Merquen_com.dbo.EXPORTADORAS
  RIGHT JOIN Erpfrusys.dbo.EXPORTADORES ON EXPORTADORAS.COD_EXP = EXPORTADORES.COD_EXP;