SELECT
  COD_SIT AS NAVE,
  GUIA_DESP AS ORDEN_DESPACHO,
  NRO_CONT AS CONTENEDOR,
  LOTE AS FOLIO,
  VARIEDA_ETIQUETADA AS VARIEDAD,
  CAJAS,
  CAJAS * NETO AS KILOS,
  CASE
    d.TIP_TRA
    WHEN 'M' THEN 'MARITIMO'
    WHEN 'A' THEN 'AEREO'
    WHEN 'T' THEN 'TERRESTRE'
    WHEN 'V' THEN 'VENTA NACIONAL'
    WHEN 'S' THEN 'SERVICIO'
    WHEN 'Z' THEN 'SOPORTES'
    WHEN 'R' THEN 'RESERVAS'
    WHEN 'I' THEN 'VENTA MERCADO INTERNO'
    ELSE 'ERROR'
  END AS TIPO_NAVE,
  NOM_ESP AS ESPECIE,
  GUIA_DES AS GUIA_DESPACHO
FROM
  Erpfrusys.dbo.UNE_DESPACHOS_MIXTOS AS d
WHERE
  (COD_TEM = 5)
  AND (COD_EMP = 'MER')
  AND (COD_SIT IN ('100', '0023'));