SELECT
  EX.COD_TEM AS TEMPORADA,
  ISNULL(MEX.COD_EMP, EX.COD_EMP) AS EMPRESA,
  EX.LOTE,
  ISNULL(MEX.COD_ENVOP, EX.COD_ENVOP) AS ENVASE,
  ISNULL(MEX.CAJAS, EX.CAJAS) AS CAJA,
  ISNULL(EX.TIP_LOT, MEX.TIP_LOT) AS TIPLOTE,
  ISNULL(EX.TIPO_LOT, MEX.TIPO_LOT) AS TLOTE,
  ISNULL(EX.ALTURA, MEX.ALTURA) AS ALTURA,
  ENO.CPL_ENV AS CAJAxENVASE
FROM
  Erpfrusys.dbo.EXISTENCIA AS EX
  LEFT JOIN Erpfrusys.dbo.MIXEXISTENCIA AS MEX ON EX.COD_TEM = MEX.COD_TEM
  AND EX.COD_EMP = MEX.COD_EMP
  AND EX.LOTE = MEX.LOTE
  LEFT JOIN Erpfrusys.dbo.ENVASEOPERACIONAL AS ENO ON EX.COD_TEM = ENO.COD_TEM
  AND EX.COD_EMP = ENO.COD_EMP
  AND ENO.COD_ENVOP = ISNULL(EX.COD_ENVOP, MEX.COD_ENVOP);