SELECT
  E.LOTE,
  ISNULL(ME.COD_ENVOP, E.COD_ENVOP) AS COD_ENVOP,
  ISNULL(ME.CAJAS, E.CAJAS) AS CAJAS,
  E.COD_EMP,
  E.COD_TEM,
  OP.CPL_ENV,
  ISNULL(ME.TIP_LOT, E.TIP_LOT) AS TIP_LOT,
  ISNULL(ME.TIPO_LOT, E.TIPO_LOT) AS TIPO_LOT,
  ISNULL(ME.ALTURA, E.ALTURA) AS ALTURA
FROM
  Erpfrusys.dbo.EXISTENCIA AS E
  LEFT JOIN Erpfrusys.dbo.MIXEXISTENCIA AS ME ON E.LOTE = ME.LOTE
  AND E.COD_EMP = ME.COD_EMP
  AND E.COD_TEM = ME.COD_TEM
  LEFT JOIN Erpfrusys.dbo.ENVASEOPERACIONAL AS OP ON OP.COD_ENVOP = ISNULL(ME.COD_ENVOP, E.COD_ENVOP)
  AND E.COD_EMP = OP.COD_EMP
  AND E.COD_TEM = OP.COD_TEM;