SELECT
  P.COD_TEM,
  P.COD_EMP,
  P.COD_PRO,
  P.NOM_PRO,
  P.GGN,
  P.CSG,
  PX.COD_EXP,
  EXP.NOM_EXP,
  CU.COD_CUA,
  ES.NOM_ESP,
  VA.NOM_VAR,
  CU.COD_PRE
FROM
  Erpfrusys.dbo.PRODUCTORES AS P
  LEFT JOIN Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR AS PX ON P.COD_PRO = PX.COD_PRO
  AND P.COD_TEM = PX.COD_TEM
  AND P.COD_EMP = PX.COD_EMP
  LEFT JOIN Erpfrusys.dbo.EXPORTADORES AS EXP ON PX.COD_EXP = EXP.COD_EXP
  AND P.COD_TEM = EXP.COD_TEM
  AND P.COD_EMP = EXP.COD_EMP
  LEFT JOIN Erpfrusys.dbo.CUARTELES AS CU ON P.COD_TEM = CU.COD_TEM
  AND P.COD_EMP = CU.COD_EMP
  AND P.COD_PRO = CU.COD_PRO
  LEFT JOIN Erpfrusys.dbo.ESPECIE AS ES ON CU.COD_TEM = ES.COD_TEM
  AND CU.COD_EMP = ES.COD_EMP
  AND CU.COD_ESP = ES.COD_ESP
  LEFT JOIN Erpfrusys.dbo.VARIEDAD AS VA ON P.COD_TEM = VA.COD_TEM
  AND P.COD_EMP = VA.COD_EMP
  AND CU.COD_ESP = VA.COD_ESP
  AND CU.COD_VAR = VA.COD_VAR;