SELECT
  P.COD_TEM,
  P.COD_EMP,
  P.COD_PRO,
  P.NOM_PRO,
  PX.COD_EXP,
  EX.NOM_EXP
FROM
  Erpfrusys.dbo.PRODUCTORES AS P
  LEFT JOIN Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR AS PX ON P.COD_PRO = PX.COD_PRO
  LEFT JOIN Erpfrusys.dbo.EXPORTADORES AS EX ON PX.COD_EXP = EX.COD_EXP;