SELECT
  GRAN.LOTE,
  GRAN.COD_VAR,
  GRAN.COD_ESP,
  GRAN.COD_TEM,
  V.NOM_VAR
FROM
  Erpfrusys.dbo.RECEPACK AS GRAN
  LEFT JOIN Erpfrusys.DBO.VARIEDAD AS v ON V.COD_VAR = GRAN.COD_VAR
WHERE
  v.cod_tem = 6
UNION
SELECT
  PTER.LOTE,
  PTER.COD_VAR,
  PTER.COD_ESP,
  PTER.COD_TEM,
  V.NOM_VAR
FROM
  Erpfrusys.dbo.PROPACKLOTE AS PTER
  LEFT JOIN Erpfrusys.DBO.VARIEDAD AS v ON V.COD_VAR = PTER.COD_VAR
WHERE
  v.cod_tem = 6
UNION
SELECT
  repa.LOTE,
  repa.COD_VAR,
  REPA.COD_ESP,
  REPA.COD_TEM,
  V.NOM_VAR
FROM
  Erpfrusys.dbo.REPALETIZADOS AS repa
  LEFT JOIN Erpfrusys.DBO.VARIEDAD AS v ON V.COD_VAR = repa.COD_VAR
WHERE
  v.cod_tem = 6;