SELECT
  P.COD_PRO,
  P.NOM_PRO,
  PXE.COD_EXP,
  P.COD_EMP,
  P.COD_TEM,
  E.NOM_EXP
FROM
  Erpfrusys.dbo.PRODUCTORES AS P
  LEFT JOIN Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR AS PXE ON P.COD_PRO = PXE.COD_PRO
  AND P.COD_TEM = PXE.COD_TEM
  AND P.COD_EMP = PXE.COD_EMP
  LEFT JOIN Erpfrusys.dbo.EXPORTADORES AS E ON PXE.COD_EXP = E.COD_EXP
  AND PXE.COD_TEM = E.COD_TEM
  AND PXE.COD_EMP = E.COD_EMP;