SELECT
  csd.COD_EMP AS Empresa,
  csd.COD_TEM AS Temporada,
  VARIEDAD.COD_ESP,
  VARIEDAD.COD_VAR,
  VARIEDAD.NOM_VAR,
  csd.PLANILLA AS Planilla,
  cps.DESCRIPCION AS Segregacion,
  ctd.DESCRIPCION AS Parametro,
  csd.VALOR AS Valor,
  CASE
    WHEN ctd.DESCRIPCION = 'FIRMEZA' THEN 8
    WHEN ctd.DESCRIPCION = 'CALIBRE' THEN 7
    WHEN ctd.DESCRIPCION = 'BRIX' THEN 6
    WHEN ctd.DESCRIPCION = 'COLOR 4+5' THEN 5
    WHEN ctd.DESCRIPCION = 'PARTIDURAS SEVERAS + HERIDAS ABIERTAS' THEN 4
    WHEN ctd.DESCRIPCION = 'PUDRICIONES + DAÑO PAJARO' THEN 3
    WHEN ctd.DESCRIPCION = 'MACHUCONES + FRUTA BLANDA' THEN 2
    WHEN ctd.DESCRIPCION = 'PEDICELOS DESHIDRATADOS' THEN 1
    ELSE '0'
  END AS 'Peso_Motivo',
  CASE
    WHEN cps.DESCRIPCION = 'PREMIUM SELECT' THEN 1
    WHEN cps.DESCRIPCION = 'PREMIUM' THEN 2
    WHEN cps.DESCRIPCION = 'VALUE' THEN 3
    WHEN cps.DESCRIPCION = 'SPECIAL' THEN 4
    WHEN cps.DESCRIPCION = 'RECHAZO' THEN 5
    ELSE '0'
  END AS 'Peso_Segregacion'
FROM
  Erpfrusys.dbo.CTRL_SEG_DATOS AS csd
  LEFT JOIN Erpfrusys.dbo.CTRL_TIPO_SEGREGACION AS ctd ON csd.COD_TEM = ctd.COD_TEM
  AND csd.COD_EMP = ctd.COD_EMP
  AND csd.COD_TIPO_SEG = ctd.COD_TIPO_SEG
  LEFT JOIN Erpfrusys.dbo.CTRL_PERIODO_SEGREGACION AS cps ON csd.COD_TEM = cps.COD_TEM
  AND csd.COD_EMP = cps.COD_EMP
  AND csd.COD_PERIODO_SEG = cps.COD_PERIODO_SEG
  JOIN Erpfrusys.dbo.RECEPACK ON RECEPACK.COD_EMP = csd.COD_EMP
  AND RECEPACK.COD_TEM = csd.COD_TEM
  AND RECEPACK.PLANILLA = csd.PLANILLA
  JOIN Erpfrusys.dbo.VARIEDAD ON RECEPACK.COD_ESP = VARIEDAD.COD_ESP
  AND RECEPACK.COD_VAR = VARIEDAD.COD_VAR
  AND VARIEDAD.COD_TEM = csd.COD_TEM
  AND VARIEDAD.COD_EMP = csd.COD_EMP
WHERE
  csd.COD_TEM = 7
  AND RECEPACK.TIPOFRU = 'E'
  AND recepack.cod_esp = '5';