SELECT
  TOP (100) PERCENT OLX.COD_EMP,
  OLX.COD_TEM,
  OLX.ZON,
  OLX.NRO_ORDEN,
  OLX.COD_ESP,
  OLX.COD_VAR,
  ISNULL(OLX.COD_PRO_ETI, PKX.COD_PRO) AS COD_PRO_ETI,
  ISNULL(OLX.COD_VAR_ETI, PKX.COD_VAR) AS COD_VAR_ETI,
  ISNULL(OLX.COD_CUA_ETI, TPX.COD_CUA) AS COD_CUA_ETI,
  SUM(OLX.CANTIDAD) AS CANTIDAD,
  SUM(OLX.TOTAL_KILOS) AS TOTAL_KILOS,
  (
    SELECT
      MAX(PLANILLA) AS Expr1
    FROM
      Erpfrusys.dbo.PROCEPACK AS X1
    WHERE
      (COD_EMP = OLX.COD_EMP)
      AND (COD_TEM = OLX.COD_TEM)
      AND (ZON = OLX.ZON)
      AND (LOTE = OLX.LOTE)
  ) AS prpk,
  (
    SELECT
      MIN(PLANILLA) AS Expr1
    FROM
      Erpfrusys.dbo.PROCEPACK AS X1
    WHERE
      (COD_EMP = OLX.COD_EMP)
      AND (COD_TEM = OLX.COD_TEM)
      AND (ZON = OLX.ZON)
      AND (LOTE = OLX.LOTE)
  ) AS prpk_OR,
  OLX.LOTE,
  (
    SELECT
      MIN(LOTE) AS Expr1
    FROM
      Erpfrusys.dbo.PROCEPACK AS pc
    WHERE
      (
        PLANILLA = (
          SELECT
            MIN(PLANILLA) AS Expr1
          FROM
            Erpfrusys.dbo.PROCEPACK AS X1
          WHERE
            (COD_EMP = OLX.COD_EMP)
            AND (COD_TEM = OLX.COD_TEM)
            AND (ZON = OLX.ZON)
            AND (LOTE = OLX.LOTE)
        )
      )
      AND (TIPOFRU = 'p')
  ) AS x_lote
FROM
  Erpfrusys.dbo.ORDEN_EMBALAJE_LOTES AS OLX
  LEFT JOIN Erpfrusys.dbo.TIT_PROCEPACK AS TPX ON TPX.COD_EMP = OLX.COD_EMP
  AND TPX.COD_TEM = OLX.COD_TEM
  AND TPX.ZON = OLX.ZON
  AND TPX.PLANILLA = (
    SELECT
      MAX(PLANILLA) AS Expr1
    FROM
      Erpfrusys.dbo.PROCEPACK AS X
    WHERE
      (COD_EMP = OLX.COD_EMP)
      AND (COD_TEM = OLX.COD_TEM)
      AND (ZON = OLX.ZON)
      AND (LOTE = OLX.LOTE)
  )
  LEFT JOIN Erpfrusys.dbo.PROCEPACK AS PKX ON PKX.COD_EMP = TPX.COD_EMP
  AND PKX.COD_TEM = OLX.COD_TEM
  AND TPX.COD_EMP = PKX.COD_EMP
  AND TPX.PLANILLA = PKX.PLANILLA
  AND TPX.ZON = PKX.ZON
  AND PKX.ZON = OLX.ZON
  AND PKX.PLANILLA = TPX.PLANILLA
  AND PKX.LOTE = OLX.LOTE
GROUP BY
  OLX.COD_EMP,
  OLX.COD_TEM,
  OLX.ZON,
  OLX.NRO_ORDEN,
  OLX.COD_ESP,
  OLX.COD_VAR,
  ISNULL(OLX.COD_PRO_ETI, PKX.COD_PRO),
  ISNULL(OLX.COD_VAR_ETI, PKX.COD_VAR),
  ISNULL(OLX.COD_CUA_ETI, TPX.COD_CUA),
  OLX.LOTE
ORDER BY
  OLX.COD_TEM DESC,
  OLX.NRO_ORDEN DESC;