SELECT
  TOP (100) PERCENT Temporada,
  Empresa,
  NumeroMixtos,
  AlturaPallet,
  Planilla,
  [Fecha Proceso],
  Fecha,
  Semana,
  CodigoEnvase,
  CodigoEmbalaje,
  CodigoProductorReal,
  CodProductorEtiquetado,
  NombreProductorEtiquetado,
  CodigoEspecie,
  CodigoVariedad,
  Calibre,
  Categoria,
  CodigoPacking,
  Etiqueta,
  [Nombre Etiqueta],
  CodigoDeFrigorifico,
  Plu,
  NumeroPallet,
  Cajas,
  NombreEspecie,
  NombreVariedad,
  [Variedad Packing],
  [Nombre Variedad Packing],
  NombreProductorReal,
  SUBSTRING(
    NombrePacking
    FROM
      1 FOR 60
  ) AS NombrePacking,
  NombreFrio,
  NombreEnvase,
  CodigoEnvop,
  NombreEnvop,
  Zona,
  [Número Guía],
  NotaControlCalidad,
  NotaGeneralControlCalidad,
  CajasEquivalentes,
  [Total Kilos Envase Operacional],
  [Peso Neto Envase Operacional],
  Origen,
  [Tipo Proceso],
  [Calibre Equivalente],
  [Nombre Grupo Productores],
  [Codigo Grupo Productores],
  Inicio,
  Termino,
  A;