SELECT
  mer.COD_EMP AS PLANTA,
  que.COD_EMP AS EXPORTADORA,
  e.NOM_ESP AS ESPECIE,
  mer.COD_EMB AS [EMBALAJE MERQUEN],
  que.COD_EMB AS [EMBALAJE QUELEN],
  mer.PESO_NETO AS [PESO NETO MERQUEN],
  que.PESO_NETO AS [PESO NETO QUELEN],
  mer.PESO_BRUTO AS [PESO BRUTO MERQUEN],
  que.PESO_BRUTO AS [PESO BRUTO QUELEN]
FROM
  Erpfrusys.dbo.ENVASEOPERACIONAL AS mer
  LEFT JOIN Erpfrusys.dbo.ESPECIE AS e ON mer.COD_ESP = e.COD_ESP
  AND mer.COD_TEM = e.COD_TEM
  LEFT JOIN [192.168.1.104].[Erpfrusys].dbo.ENVASEOPERACIONAL AS que ON que.COD_TEM = mer.COD_TEM
  AND mer.COD_ESP = que.COD_ESP
  AND mer.COD_ENVOP = que.COD_ENVOP
  AND que.COD_EMP = 'QUE'
WHERE
  mer.COD_TEM = 7;