SELECT
  R.TIP_MOV,
  R.COD_TEM,
  R.COD_EMP,
  R.NRO_MIX,
  R.ALTURA,
  R.TEMP_PAC,
  R.PLANILLA,
  R.FECHA_PAC,
  R.FECHA_RPA,
  R.GUIA,
  R.COD_ENV,
  R.COD_EMB,
  R.COD_PRO,
  R.COD_ESP,
  R.COD_VAR,
  R.COD_CAL,
  R.COD_CAT,
  R.COD_PACK,
  R.COD_ETI,
  R.PLU,
  R.LOTE,
  R.CAJAS,
  R.CAJ_BAS,
  E.NOM_ESP,
  V.NOM_VAR,
  P.NOM_PRO,
  PK.NOM_PACK,
  FR.NOM_FRI,
  ENV.NOM_ENV,
  R.COD_ENVOP,
  R.ZON,
  ETI.NOM_ETI,
  r.cod_exp
FROM
  ERPFRUSYS.DBO.RECEPCION AS R
  JOIN ERPFRUSYS.DBO.ESPECIE AS E ON R.COD_ESP = E.COD_ESP
  AND R.COD_TEM = E.COD_TEM
  AND R.COD_EMP = E.COD_EMP
  JOIN ERPFRUSYS.DBO.VARIEDAD AS V ON R.COD_ESP = V.COD_ESP
  AND R.COD_VAR = V.COD_VAR
  AND R.COD_TEM = V.COD_TEM
  AND R.COD_EMP = V.COD_EMP
  JOIN ERPFRUSYS.DBO.PRODUCTORES AS P ON R.COD_PRO = P.COD_PRO
  AND R.COD_TEM = P.COD_TEM
  AND R.COD_EMP = P.COD_EMP
  JOIN ERPFRUSYS.DBO.PACKINGS AS PK ON R.COD_PACK = PK.COD_PACK
  AND R.COD_TEM = PK.COD_TEM
  AND R.COD_EMP = PK.COD_EMP
  JOIN ERPFRUSYS.DBO.FRIOS AS FR ON R.COD_FRI = FR.COD_FRI
  AND R.COD_TEM = FR.COD_TEM
  AND R.COD_EMP = FR.COD_EMP
  JOIN ERPFRUSYS.DBO.ENVASE AS ENV ON R.COD_ENV = ENV.COD_ENV
  AND R.COD_TEM = ENV.COD_TEM
  AND R.COD_EMP = ENV.COD_EMP
  JOIN ERPFRUSYS.DBO.ETIQUETA AS ETI ON ETI.COD_ETI = R.COD_ETI
  AND R.COD_TEM = ETI.COD_TEM
  AND R.COD_EMP = ETI.COD_EMP
WHERE
  R.NRO_MIX = 0
UNION
ALL
SELECT
  MR.TIP_MOV,
  MR.COD_TEM,
  MR.COD_EMP,
  MR.NRO_MIX,
  MR.ALTURA,
  MR.TEMP_PAC,
  MR.PLANILLA,
  MR.FECHA_PAC,
  MR.FECHA_RPA,
  MR.GUIA,
  MR.COD_ENV,
  MR.COD_EMB,
  MR.COD_PRO,
  MR.COD_ESP,
  MR.COD_VAR,
  MR.COD_CAL,
  MR.COD_CAT,
  MR.COD_PACK,
  MR.COD_ETI,
  MR.PLU,
  MR.LOTE,
  MR.CAJAS,
  MR.CAJ_BAS,
  E.NOM_ESP,
  V.NOM_VAR,
  P.NOM_PRO,
  PK.NOM_PACK,
  FR.NOM_FRI,
  ENV.NOM_ENV,
  MR.COD_ENVOP,
  MR.ZON,
  ETI.NOM_ETI,
  mr.cod_exp
FROM
  ERPFRUSYS.DBO.MIXRECEPCION AS MR
  JOIN ERPFRUSYS.DBO.ESPECIE AS E ON MR.COD_ESP = E.COD_ESP
  AND MR.COD_TEM = E.COD_TEM
  AND MR.COD_EMP = E.COD_EMP
  JOIN ERPFRUSYS.DBO.VARIEDAD AS V ON MR.COD_ESP = V.COD_ESP
  AND MR.COD_VAR = V.COD_VAR
  AND MR.COD_TEM = V.COD_TEM
  AND MR.COD_EMP = V.COD_EMP
  JOIN ERPFRUSYS.DBO.PRODUCTORES AS P ON MR.COD_PRO = P.COD_PRO
  AND MR.COD_TEM = P.COD_TEM
  AND MR.COD_EMP = P.COD_EMP
  JOIN ERPFRUSYS.DBO.PACKINGS AS PK ON MR.COD_PACK = PK.COD_PACK
  AND MR.COD_TEM = PK.COD_TEM
  AND MR.COD_EMP = PK.COD_EMP
  JOIN ERPFRUSYS.DBO.FRIOS AS FR ON MR.COD_FRI = FR.COD_FRI
  AND MR.COD_TEM = FR.COD_TEM
  AND MR.COD_EMP = FR.COD_EMP
  JOIN ERPFRUSYS.DBO.ENVASE AS ENV ON MR.COD_ENV = ENV.COD_ENV
  AND MR.COD_TEM = ENV.COD_TEM
  AND MR.COD_EMP = ENV.COD_EMP
  JOIN ERPFRUSYS.DBO.ETIQUETA AS ETI ON ETI.COD_ETI = MR.COD_ETI
  AND MR.COD_TEM = ETI.COD_TEM
  AND MR.COD_EMP = ETI.COD_EMP;