SELECT
  'Salidas de Reem.' AS TIPO,
  COD_TEM,
  COD_EMP,
  PLANILLA,
  FECHA_RPA,
  COD_PRO,
  COD_FRI,
  COD_ESP,
  COD_VAR,
  LOTE,
  ZON,
  CAJAS,
  TOTAL_KILOS,
  KILOS,
  NOM_PRO,
  NOM_VAR,
  NOM_FRI,
  NOM_ESP,
  COD_CAL,
  COD_ENVOP,
  COD_ETI,
  TIPO AS Expr1,
  COD_TIPO_TRA,
  NOM_TIPO_TRA,
  COD_PRE,
  COD_EXP
FROM
  (
    SELECT
      DISTINCT PK.COD_TEM,
      PK.COD_EMP,
      PK.PLANILLA,
      PK.FECHA_RPA,
      PK.COD_PRO,
      PK.COD_FRI,
      V.COD_ESP,
      PK.COD_VAR,
      PK.LOTE,
      PK.ZON,
      PK.CAJAS,
      EO.PESO_NETO * PK.CAJAS AS TOTAL_KILOS,
      EO.PESO_NETO AS KILOS,
      P.NOM_PRO,
      V.NOM_VAR,
      Erpfrusys.dbo.FRIOS.NOM_FRI,
      E.NOM_ESP,
      PK.COD_CAL,
      PK.COD_ENVOP,
      PK.COD_ETI,
      'Creado' AS TIPO,
      PK.COD_TIPO_TRA,
      TIPO.DESCRIPCION AS NOM_TIPO_TRA,
      PK.COD_PRE,
      0 AS CORRELATIVO,
      PK.COD_EXP
    FROM
      Erpfrusys.dbo.PROPACKLOTE_MAS AS PK
      JOIN Erpfrusys.dbo.PRODUCTORES AS P ON PK.COD_PRO = P.COD_PRO
      AND PK.COD_TEM = P.COD_TEM
      AND PK.COD_EMP = P.COD_EMP
      JOIN Erpfrusys.dbo.ESPECIE AS E ON PK.COD_ESP = E.COD_ESP
      AND PK.COD_TEM = E.COD_TEM
      AND PK.COD_EMP = E.COD_EMP
      JOIN Erpfrusys.dbo.VARIEDAD AS V ON PK.COD_VAR = V.COD_VAR
      AND E.COD_ESP = V.COD_ESP
      AND PK.COD_TEM = V.COD_TEM
      AND PK.COD_EMP = V.COD_EMP
      JOIN Erpfrusys.dbo.FRIOS ON PK.COD_FRI = Erpfrusys.dbo.FRIOS.COD_FRI
      AND PK.COD_TEM = Erpfrusys.dbo.FRIOS.COD_TEM
      AND PK.COD_EMP = Erpfrusys.dbo.FRIOS.COD_EMP
      JOIN Erpfrusys.dbo.ENVASEOPERACIONAL AS EO ON EO.COD_EMP = PK.COD_EMP
      AND EO.COD_TEM = PK.COD_TEM
      AND EO.COD_ENVOP = PK.COD_ENVOP
      LEFT JOIN Erpfrusys.dbo.TIPO_TRATAMIENTO AS TIPO ON TIPO.COD_EMP = PK.COD_EMP
      AND TIPO.COD_TEM = PK.COD_TEM
      AND TIPO.COD_TIPO_TRA = PK.COD_TIPO_TRA
      AND TIPO.COD_ESP = PK.COD_ESP
    WHERE
      (PK.NRO_MIX = 0)
    UNION
    ALL
    SELECT
      DISTINCT PK.COD_TEM,
      PK.COD_EMP,
      PK.PLANILLA,
      PK.FECHA_RPA,
      PK.COD_PRO,
      PK.COD_FRI,
      V.COD_ESP,
      PK.COD_VAR,
      PK.LOTE,
      PK.ZON,
      PK.CAJAS,
      EO.PESO_NETO * PK.CAJAS AS TOTAL_KILOS,
      EO.PESO_NETO AS KILOS,
      P.NOM_PRO,
      V.NOM_VAR,
      FRIOS_1.NOM_FRI,
      E.NOM_ESP,
      PK.COD_CAL,
      PK.COD_ENVOP,
      PK.COD_ETI,
      'Creado' AS TIPO,
      PK.COD_TIPO_TRA,
      TIPO.DESCRIPCION AS NOM_TIPO_TRA,
      PK.COD_PRE,
      PK.CORRELATIVO,
      PK.COD_EXP
    FROM
      Erpfrusys.dbo.PROPACKMIX_MAS AS PK
      JOIN Erpfrusys.dbo.PRODUCTORES AS P ON PK.COD_PRO = P.COD_PRO
      AND PK.COD_TEM = P.COD_TEM
      AND PK.COD_EMP = P.COD_EMP
      JOIN Erpfrusys.dbo.ESPECIE AS E ON PK.COD_ESP = E.COD_ESP
      AND PK.COD_TEM = E.COD_TEM
      AND PK.COD_EMP = E.COD_EMP
      JOIN Erpfrusys.dbo.VARIEDAD AS V ON PK.COD_VAR = V.COD_VAR
      AND E.COD_ESP = V.COD_ESP
      AND PK.COD_TEM = V.COD_TEM
      AND PK.COD_EMP = V.COD_EMP
      JOIN Erpfrusys.dbo.FRIOS AS FRIOS_1 ON PK.COD_FRI = FRIOS_1.COD_FRI
      AND PK.COD_TEM = FRIOS_1.COD_TEM
      AND PK.COD_EMP = FRIOS_1.COD_EMP
      JOIN Erpfrusys.dbo.ENVASEOPERACIONAL AS EO ON EO.COD_EMP = PK.COD_EMP
      AND EO.COD_TEM = PK.COD_TEM
      AND EO.COD_ENVOP = PK.COD_ENVOP
      LEFT JOIN Erpfrusys.dbo.TIPO_TRATAMIENTO AS TIPO ON TIPO.COD_EMP = PK.COD_EMP
      AND TIPO.COD_TEM = PK.COD_TEM
      AND TIPO.COD_TIPO_TRA = PK.COD_TIPO_TRA
      AND TIPO.COD_ESP = PK.COD_ESP
  ) AS P_1;