SELECT
  ISNULL(ED.LOTE, E.LOTE) AS LOTE,
  E.COD_EMP,
  E.COD_TEM,
  ISNULL(ED.ZON, E.ZON) AS ZON,
  ISNULL(ED.PLANILLA, E.PLANILLA) AS PLANILLA,
  ISNULL(ED.FECHA_RPA, E.FECHA_RPA) AS FECHA_RPA,
  ISNULL(ED.COD_PACK, E.COD_PACK) AS COD_PACK,
  ISNULL(ED.COD_PRO, E.COD_PRO) AS COD_PRO,
  ISNULL(ED.COD_FRI, E.COD_FRI) AS COD_FRI,
  ISNULL(ED.COD_ESP, E.COD_ESP) AS COD_ESP,
  ISNULL(ED.COD_VAR, E.COD_VAR) AS COD_VAR,
  ISNULL(ED.COD_CAL, E.COD_CAL) AS COD_CAL,
  ISNULL(ED.HORA_REC, E.HORA_REC) AS HORA_REC,
  ISNULL(ED.COD_ENV, E.COD_ENV) AS COD_ENV,
  ISNULL(ED.CANTIDAD, E.CANTIDAD) AS CANTIDAD,
  ED.KILOS_BRUTO,
  ED.KILOS_BINS,
  E.KILOS,
  ISNULL(ED.TIPOFRU, E.TIPOFRU) AS TIPOFRU,
  ISNULL(ED.T_PROCESO, E.T_PROCESO) AS T_PROCESO,
  ISNULL(ED.COD_JORNADA, E.COD_JORNADA) AS COD_JORNADA,
  ISNULL(ED.GUIA, E.GUIA) AS GUIA,
  ISNULL(ED.VALOR, E.VALOR) AS VALOR,
  ISNULL(ED.VENT_KILOS, E.VENT_KILOS) AS VENT_KILOS,
  ISNULL(ED.COD_CALIDAD, E.COD_CALIDAD) AS COD_CALIDAD,
  ISNULL(ED.COD_PRE, E.COD_PRE) AS COD_PRE,
  ISNULL(ED.COD_CUA, E.COD_CUA) AS COD_CUA,
  ED.ORDEN_ING,
  ISNULL(ED.TOTAL_KILOS, E.TOTAL_KILOS) AS TOTAL_KILOS,
  ED.CANT_ENV_CONT,
  ISNULL(ED.COD_CAM, E.COD_CAM) AS COD_CAM,
  ISNULL(ED.COD_BANDA, E.COD_BANDA) AS COD_BANDA,
  ISNULL(ED.FILA, E.FILA) AS FILA,
  ISNULL(ED.PISO, E.PISO) AS PISO,
  E.COD_TIPO_TRA,
  E.CANT_ENV_CONT AS Expr1,
  E.NRO_MIX,
  ED.PROCESO,
  ISNULL(ED.NotaCalidad, E.NotaCalidad) AS NotaCalidad,
  ISNULL(ED.Velocidad, E.Velocidad) AS Velocidad,
  ED.COD_TIPO_RECEPCION_PACK,
  P.NOM_PRO,
  ESP.NOM_ESP,
  V.NOM_VAR,
  ENV.NOM_ENV,
  PXE.COD_EXP,
  EXP.NOM_EXP,
  CAL.DESCRIPCION
FROM
  Erpfrusys.dbo.EXISPACK AS E
  LEFT JOIN Erpfrusys.dbo.EXISPACK_DET AS ED ON E.LOTE = ED.LOTE
  AND E.COD_TEM = ED.COD_TEM
  AND E.COD_EMP = ED.COD_EMP
  LEFT JOIN Erpfrusys.dbo.PRODUCTORES AS P ON ED.COD_PRO = P.COD_PRO
  AND ED.COD_TEM = P.COD_TEM
  AND ED.COD_EMP = P.COD_EMP
  LEFT JOIN Erpfrusys.dbo.ESPECIE AS ESP ON ISNULL(ED.COD_ESP, E.COD_ESP) = ESP.COD_ESP
  AND E.COD_EMP = ESP.COD_EMP
  AND E.COD_TEM = ESP.COD_TEM
  LEFT JOIN Erpfrusys.dbo.VARIEDAD AS V ON ISNULL(ED.COD_VAR, E.COD_VAR) = V.COD_VAR
  AND E.COD_EMP = V.COD_EMP
  AND E.COD_TEM = V.COD_TEM
  LEFT JOIN Erpfrusys.dbo.ENVASE AS ENV ON ED.COD_ENV = ENV.COD_ENV
  AND ED.COD_EMP = ENV.COD_EMP
  AND ED.COD_TEM = ENV.COD_TEM
  LEFT JOIN Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR AS PXE ON ISNULL(ED.COD_PRO, E.COD_PRO) = PXE.COD_PRO
  AND E.COD_EMP = PXE.COD_EMP
  AND E.COD_TEM = PXE.COD_TEM
  LEFT JOIN Erpfrusys.dbo.EXPORTADORES AS EXP ON PXE.COD_EXP = EXP.COD_EXP
  AND E.COD_EMP = EXP.COD_EMP
  AND E.COD_TEM = EXP.COD_TEM
  LEFT JOIN Erpfrusys.dbo.CALIBRES AS CAL ON ED.COD_CAL = CAL.COD_CAL
  AND E.COD_EMP = CAL.COD_EMP
  AND E.COD_TEM = CAL.COD_TEM
  AND ED.COD_ESP = CAL.COD_ESP;