SELECT
  T.COD_EMP,
  T.COD_TEM,
  T.FECHA_RPA,
  T.COD_JORNADA,
  T.COD_LINEA,
  T.NRO_ORDEN,
  T.PLANILLA,
  T.T_PROCESO,
  P1.TOTAL_KILOS AS KILOS,
  P1.LOTE,
  P1.COD_PRE,
  P1.COD_CALIDAD,
  P1.CANTIDAD,
  CASE
    WHEN P1.COD_ENVOP = '' THEN p1.cod_env
    WHEN P1.COD_ENVOP IS NULL THEN p1.cod_env
    ELSE p1.cod_envop
  END AS cod_envop,
  ISNULL(
    P1.COD_EXP,
    (
      SELECT
        COD_EXP
      FROM
        Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR AS EP
      WHERE
        (COD_PRO = P1.COD_PRO)
        AND (P1.COD_TEM = COD_TEM)
        AND (COD_EMP = P1.COD_EMP)
    )
  ) AS COD_EXP,
  P1.COD_CAL,
  P1.COD_VAR,
  P1.COD_ESP,
  [VAR].NOM_VAR,
  VARP.NOM_VAR AS NOM_VAR_PROCESO,
  ESP.NOM_ESP,
  P1.COD_ENV,
  P1.COD_PRO,
  P1.TIPOFRU,
  0 AS neto_std,
  P1.COD_CUA,
  tr.FECHA_DIGITA AS fecha_recepcion,
  tt.FECHA_COSECHA,
  ULP.LVL_Data_Inizio AS FECHA_INICIO_PROCESO,
  'SIN PROCESAR' AS CATEGORIA,
  P1.COD_PACK
FROM
  Erpfrusys.dbo.PROCEPACK AS P1
  JOIN Erpfrusys.dbo.TIT_PROCEPACK AS T ON P1.ZON = T.ZON
  AND P1.PLANILLA = T.PLANILLA
  AND P1.COD_EMP = T.COD_EMP
  AND P1.COD_TEM = T.COD_TEM
  LEFT JOIN Erpfrusys.dbo.ESPECIE AS ESP ON P1.COD_TEM = ESP.COD_TEM
  AND P1.COD_EMP = ESP.COD_EMP
  AND P1.COD_ESP = ESP.COD_ESP
  LEFT JOIN Erpfrusys.dbo.VARIEDAD AS [VAR] ON P1.COD_EMP = [VAR].COD_EMP
  AND P1.COD_TEM = [VAR].COD_TEM
  AND P1.COD_VAR = [VAR].COD_VAR
  AND [VAR].COD_ESP = P1.COD_ESP
  LEFT JOIN Erpfrusys.dbo.VARIEDAD AS VARP ON P1.COD_EMP = VARP.COD_EMP
  AND P1.COD_TEM = VARP.COD_TEM
  AND T.COD_VAR = VARP.COD_VAR
  AND VARP.COD_ESP = P1.COD_ESP
  LEFT JOIN Erpfrusys.dbo.RECEPACK AS tr ON P1.LOTE = tr.LOTE
  AND P1.COD_EMP = tr.COD_EMP
  AND P1.COD_TEM = tr.COD_TEM
  LEFT JOIN Erpfrusys.dbo.TIT_RECEPACK AS tt ON CONVERT(nvarchar, tt.PLANILLA) = REPLACE(LTRIM(REPLACE(P1.LOTE, '0', ' ')), ' ', '0')
  AND P1.COD_EMP = tt.COD_EMP
  AND P1.COD_TEM = tt.COD_TEM
  LEFT JOIN UNITEC.UNITEC_DB_SDT.dbo.v_lote_proceso AS ULP ON ULP.LOT_DDT = tr.PLANILLA
  AND P1.PLANILLA = ULP.proceso
WHERE
  (P1.TIPOFRU_PK = 'E')
  AND (T.ZON = 'C')
  AND (T.COD_EMP = 'MER')
  OR (P1.TIPOFRU_PK = 'P')
  AND (T.ZON = 'C')
  AND (T.COD_EMP = 'MER')
  AND (T.T_PROCESO = 'PreProceso');