SELECT
  T.COD_EMP,
  T.COD_TEM,
  T.FECHA_RPA,
  T.COD_JORNADA,
  T.COD_LINEA,
  T.NRO_ORDEN,
  T.PLANILLA,
  T.T_PROCESO,
  P.TOTAL_KILOS,
  P.LOTE,
  P.COD_PRE,
  P.COD_CALIDAD,
  P.CANTIDAD,
  CASE
    WHEN P.COD_ENVOP = '' THEN p.cod_env
    WHEN P.COD_ENVOP IS NULL THEN p.cod_env
    ELSE p.cod_envop
  END AS COD_ENVOP,
  ISNULL(
    P.COD_EXP,
    (
      SELECT
        COD_EXP
      FROM
        Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR AS EP
      WHERE
        (COD_PRO = P.COD_PRO)
        AND (P.COD_TEM = COD_TEM)
        AND (COD_EMP = P.COD_EMP)
    )
  ) AS Expr1,
  P.COD_CAL,
  P.COD_VAR,
  P.COD_ESP,
  [VAR].NOM_VAR,
  VARP.NOM_VAR AS NOM_VAR_PROCESO,
  ESP.NOM_ESP,
  P.COD_ENV,
  P.COD_PRO,
  P.TIPOFRU,
  E.PESO_NETO AS neto_std,
  P.COD_CUA,
  '' AS FECHA_RECEPCION,
  tt.FECHA_COSECHA,
  '' AS FECHA_INICIO_PROCESO,
  'Mercado Interno' AS CATEGORIA,
  P.COD_PACK
FROM
  Erpfrusys.dbo.PROCEPACK AS P
  JOIN Erpfrusys.dbo.TIT_PROCEPACK AS T ON P.PLANILLA = T.PLANILLA
  AND P.ZON = T.ZON
  AND P.COD_EMP = T.COD_EMP
  AND P.COD_TEM = T.COD_TEM
  LEFT JOIN Erpfrusys.dbo.ENVASE AS E ON P.COD_TEM = E.COD_TEM
  AND P.COD_EMP = E.COD_EMP
  AND P.COD_ENV = E.COD_ENV
  LEFT JOIN Erpfrusys.dbo.ESPECIE AS ESP ON P.COD_TEM = ESP.COD_TEM
  AND P.COD_EMP = ESP.COD_EMP
  AND P.COD_ESP = ESP.COD_ESP
  LEFT JOIN Erpfrusys.dbo.VARIEDAD AS [VAR] ON P.COD_EMP = [VAR].COD_EMP
  AND P.COD_TEM = [VAR].COD_TEM
  AND P.COD_VAR = [VAR].COD_VAR
  AND [VAR].COD_ESP = P.COD_ESP
  LEFT JOIN Erpfrusys.dbo.VARIEDAD AS VARP ON P.COD_EMP = VARP.COD_EMP
  AND P.COD_TEM = VARP.COD_TEM
  AND T.COD_VAR = VARP.COD_VAR
  AND VARP.COD_ESP = P.COD_ESP
  LEFT JOIN Erpfrusys.dbo.TIT_RECEPACK AS tt ON CONVERT(nvarchar, tt.PLANILLA) = REPLACE(LTRIM(REPLACE(P.LOTE, '0', ' ')), ' ', '0')
  AND P.COD_EMP = tt.COD_EMP
  AND P.COD_TEM = tt.COD_TEM
WHERE
  (P.TIPOFRU_PK = 'C');