SELECT
  TIT_PROCEPACK.PLANILLA,
  TIT_PROCEPACK.COD_TEM,
  TIT_PROCEPACK.COD_EMP,
  TIT_PROCEPACK.COD_PACK,
  PACKINGS.NOM_PACK,
  TIT_PROCEPACK.COD_PRO,
  PRODUCTORES.NOM_PRO,
  ESPECIE.COD_ESP,
  ESPECIE.NOM_ESP,
  VARIEDAD.COD_VAR,
  VARIEDAD.NOM_VAR,
  TIT_PROCEPACK.FECHA_RPA,
  TIT_PROCEPACK.T_PROCESO,
  PREDIOS.COD_PRE,
  PREDIOS.DESCRIPCION AS 'DES_PRE',
  CUARTELES.COD_CUA,
  CUARTELES.DESCRIPCION AS 'DES_CUA',
  TIT_PROCEPACK.COD_JORNADA,
  TIT_PROCEPACK.COD_TIPO_TRA,
  TIT_PROCEPACK_CIERRE.PLANILLA AS PLANILLA_CIERRE,
  PRODUCTOR_X_EXPORTADOR.COD_EXP,
  EXPORTADORAS.NOM_EXP,
  TIPOLINEAPK.NOM_LINEA,
  TIPOLINEAPK.COD_LINEA,
  TIT_PROCEPACK.NRO_ORDEN
FROM
  Erpfrusys.dbo.TIT_PROCEPACK
  LEFT JOIN Erpfrusys.dbo.PACKINGS ON TIT_PROCEPACK.COD_PACK = PACKINGS.COD_PACK
  AND TIT_PROCEPACK.COD_TEM = PACKINGS.COD_TEM
  AND TIT_PROCEPACK.COD_EMP = PACKINGS.COD_EMP
  LEFT JOIN Erpfrusys.dbo.PRODUCTORES ON TIT_PROCEPACK.COD_PRO = PRODUCTORES.COD_PRO
  JOIN Erpfrusys.dbo.ESPECIE ON TIT_PROCEPACK.COD_ESP = ESPECIE.COD_ESP
  AND TIT_PROCEPACK.COD_EMP = ESPECIE.COD_EMP
  AND TIT_PROCEPACK.COD_TEM = ESPECIE.COD_TEM
  LEFT JOIN Erpfrusys.dbo.VARIEDAD ON TIT_PROCEPACK.COD_VAR = VARIEDAD.COD_VAR
  AND TIT_PROCEPACK.COD_ESP = VARIEDAD.COD_ESP
  AND TIT_PROCEPACK.COD_TEM = VARIEDAD.COD_TEM
  AND TIT_PROCEPACK.COD_EMP = VARIEDAD.COD_EMP
  AND VARIEDAD.COD_ESP = ESPECIE.COD_ESP
  AND VARIEDAD.COD_TEM = ESPECIE.COD_TEM
  AND VARIEDAD.COD_EMP = ESPECIE.COD_EMP
  JOIN Erpfrusys.dbo.PREDIOS ON PREDIOS.COD_EMP = PRODUCTORES.COD_EMP
  AND PREDIOS.COD_TEM = PRODUCTORES.COD_TEM
  AND PREDIOS.COD_PRO = PRODUCTORES.COD_PRO
  JOIN Erpfrusys.dbo.CUARTELES ON TIT_PROCEPACK.COD_EMP = CUARTELES.COD_EMP
  AND TIT_PROCEPACK.COD_TEM = CUARTELES.COD_TEM
  AND TIT_PROCEPACK.COD_PRO = CUARTELES.COD_PRO
  AND TIT_PROCEPACK.COD_PRE = CUARTELES.COD_PRE
  AND TIT_PROCEPACK.COD_CUA = CUARTELES.COD_CUA
  AND CUARTELES.COD_EMP = PRODUCTORES.COD_EMP
  AND CUARTELES.COD_TEM = PRODUCTORES.COD_TEM
  AND CUARTELES.COD_PRO = PRODUCTORES.COD_PRO
  AND CUARTELES.COD_VAR = VARIEDAD.COD_VAR
  AND CUARTELES.COD_ESP = VARIEDAD.COD_ESP
  AND CUARTELES.COD_TEM = VARIEDAD.COD_TEM
  AND CUARTELES.COD_EMP = VARIEDAD.COD_EMP
  AND CUARTELES.COD_EMP = PREDIOS.COD_EMP
  AND CUARTELES.COD_TEM = PREDIOS.COD_TEM
  AND CUARTELES.COD_PRO = PREDIOS.COD_PRO
  AND CUARTELES.COD_PRE = PREDIOS.COD_PRE
  LEFT JOIN Erpfrusys.dbo.TIT_PROCEPACK_CIERRE ON TIT_PROCEPACK_CIERRE.COD_TEM = TIT_PROCEPACK.COD_TEM
  AND TIT_PROCEPACK_CIERRE.COD_EMP = TIT_PROCEPACK.COD_EMP
  AND TIT_PROCEPACK_CIERRE.PLANILLA = TIT_PROCEPACK.PLANILLA
  AND TIT_PROCEPACK_CIERRE.ZON = TIT_PROCEPACK.ZON
  AND TIT_PROCEPACK.PLANILLA = TIT_PROCEPACK_CIERRE.PLANILLA
  LEFT JOIN Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR ON PRODUCTOR_X_EXPORTADOR.COD_EMP = PRODUCTORES.COD_EMP
  AND PRODUCTOR_X_EXPORTADOR.COD_TEM = PRODUCTORES.COD_TEM
  AND PRODUCTOR_X_EXPORTADOR.COD_PRO = PRODUCTORES.COD_PRO
  LEFT JOIN Erpfrusys.dbo.EXPORTADORES AS EXPORTADORAS ON PRODUCTOR_X_EXPORTADOR.COD_EXP = EXPORTADORAS.COD_EXP
  AND PRODUCTOR_X_EXPORTADOR.COD_TEM = EXPORTADORAS.COD_TEM
  LEFT JOIN Erpfrusys.dbo.TIPOLINEAPK ON TIT_PROCEPACK.COD_EMP = TIPOLINEAPK.COD_EMP
  AND TIT_PROCEPACK.COD_TEM = TIPOLINEAPK.COD_TEM
  AND TIT_PROCEPACK.COD_LINEA = TIPOLINEAPK.COD_LINEA
WHERE
  TIT_PROCEPACK.COD_TEM = 7;