SELECT
  T.COD_EMP,
  T.COD_TEM,
  T.FECHA_RPA,
  T.COD_JORNADA,
  T.COD_LINEA,
  T.NRO_ORDEN,
  ISNULL(PM.PROCESO, p.PLANILLA) AS PLANILLA,
  T.T_PROCESO,
  ISNULL(PM.CAJAS, p.CAJAS) * ISNULL(
    Erpfrusys.dbo.AJUSTE.KILOS,
    (
      SELECT
        TOP (1) AJUSTE.KILOS
      FROM
        Erpfrusys.dbo.AJUSTE
      WHERE
        COD_ESP = p.COD_ESP
        AND COD_ENV = p.COD_ENV
        AND COD_TEM = p.COD_TEM
        AND p.COD_EMP = COD_EMP
        AND ISNULL(PM.PROCESO, p.PLANILLA) = Erpfrusys.dbo.AJUSTE.PLANILLA
    )
  ) AS TOTAL_KILOS,
  ISNULL(PM.LOTE, p.LOTE) AS lote,
  T.COD_PRE,
  p.COD_CAT,
  ISNULL(PM.CAJAS, p.CAJAS) AS CAJAS,
  p.COD_ENVOP,
  p.COD_EXP,
  ISNULL(PM.COD_CAL, p.COD_CAL) AS cod_cal,
  ISNULL(PM.COD_VAR, p.COD_VAR) AS cod_var,
  p.COD_ESP,
  [VAR].NOM_VAR,
  VARP.NOM_VAR AS NOM_VAR_PROCESO,
  ESP.NOM_ESP,
  p.COD_ENV,
  T.COD_PRO,
  'E' AS tipofru,
  E.PESO_NETO AS neto_std,
  ISNULL(PM.COD_CUA, p.COD_CUA) AS cod_cua,
  '' AS FECHA_RECEPCION,
  tt.FECHA_COSECHA,
  '' AS FECHA_INICIO_PROCESO,
  (
    SELECT
      TOP (1) NOM_CAT
    FROM
      Erpfrusys.dbo.CATEGORIA AS CT
    WHERE
      (p.COD_CAT = COD_CAT)
      AND (COD_TEM = p.COD_TEM)
      AND (COD_ESP = p.COD_ESP)
  ) AS CATEGORIA,
  p.COD_PACK,
  SUBSTRING(
    et.NOM_ETI
    FROM
      1 FOR 24
  ) AS n_etiqueta,
  ISNULL(PM.CAJAS, p.CAJAS) * Erpfrusys.dbo.AJUSTE.KILOS AS TOTAL
FROM
  Erpfrusys.dbo.PROPACKLOTE AS p
  LEFT JOIN Erpfrusys.dbo.PROPACKMIX AS PM ON p.PLANILLA = PM.PLANILLA
  AND p.COD_EMP = PM.COD_EMP
  AND PM.COD_TEM = PM.COD_TEM
  AND p.LOTE = PM.LOTE
  LEFT JOIN Erpfrusys.dbo.TIT_PROCEPACK AS T ON ISNULL(PM.PROCESO, p.PLANILLA) = T.PLANILLA
  AND p.ZON = T.ZON
  AND p.COD_EMP = T.COD_EMP
  AND p.COD_TEM = T.COD_TEM
  LEFT JOIN Erpfrusys.dbo.AJUSTE ON p.COD_EMP = Erpfrusys.dbo.AJUSTE.COD_EMP
  AND p.COD_TEM = Erpfrusys.dbo.AJUSTE.COD_TEM
  AND p.ZON = Erpfrusys.dbo.AJUSTE.ZON
  AND ISNULL(PM.PROCESO, p.PLANILLA) = Erpfrusys.dbo.AJUSTE.PLANILLA
  AND p.COD_ESP = Erpfrusys.dbo.AJUSTE.COD_ESP
  AND p.COD_ENV = Erpfrusys.dbo.AJUSTE.COD_ENV
  AND p.COD_EMB = Erpfrusys.dbo.AJUSTE.COD_EMB
  LEFT JOIN Erpfrusys.dbo.ENVASEOPERACIONAL AS E ON p.COD_TEM = E.COD_TEM
  AND p.COD_EMP = E.COD_EMP
  AND p.COD_ESP = E.COD_ESP
  AND p.COD_ENVOP = E.COD_ENVOP
  AND p.COD_EMB = E.COD_EMB
  AND p.COD_ENV = E.COD_ENV
  JOIN Erpfrusys.dbo.ESPECIE AS ESP ON p.COD_TEM = ESP.COD_TEM
  AND p.COD_EMP = ESP.COD_EMP
  AND p.COD_ESP = ESP.COD_ESP
  LEFT JOIN Erpfrusys.dbo.VARIEDAD AS [VAR] ON p.COD_EMP = [VAR].COD_EMP
  AND p.COD_TEM = [VAR].COD_TEM
  AND ISNULL(PM.COD_VAR, p.COD_VAR) = [VAR].COD_VAR
  AND [VAR].COD_ESP = p.COD_ESP
  LEFT JOIN Erpfrusys.dbo.VARIEDAD AS VARP ON p.COD_EMP = VARP.COD_EMP
  AND p.COD_TEM = VARP.COD_TEM
  AND T.COD_VAR = VARP.COD_VAR
  AND VARP.COD_ESP = p.COD_ESP
  LEFT JOIN Erpfrusys.dbo.TIT_RECEPACK AS tt ON CONVERT(nvarchar, tt.PLANILLA) = REPLACE(LTRIM(REPLACE(p.LOTE, '0', ' ')), ' ', '0')
  AND p.COD_EMP = tt.COD_EMP
  AND p.COD_TEM = tt.COD_TEM
  LEFT JOIN Erpfrusys.dbo.ETIQUETA AS et ON et.COD_EMP = p.COD_EMP
  AND et.COD_TEM = p.COD_TEM
  AND et.COD_ETI = ISNULL(PM.COD_ETI, p.COD_ETI);