SELECT
  fp.Temporada,
  fp.Empresa,
  fp.NumeroMixtos,
  fp.AlturaPallet,
  fp.Planilla,
  fp.Fecha,
  fp.Semana,
  fp.CodigoEnvase,
  fp.CodigoEmbalaje,
  fp.CodigoProductorReal,
  fp.CodigoEspecie,
  fp.CodigoVariedad,
  fp.Calibre,
  fp.Categoria,
  fp.CodigoPacking,
  fp.Etiqueta,
  fp.CodigoDeFrigorifico,
  fp.Plu,
  fp.NumeroPallet,
  fp.Cajas,
  fp.NombreEspecie,
  fp.NombreVariedad,
  fp.[Variedad Packing],
  fp.[Nombre Variedad Packing],
  fp.NombreProductorReal,
  fp.NombrePacking,
  fp.NombreFrio,
  fp.NombreEnvase,
  fp.CodigoEnvop,
  fp.NombreEnvop,
  fp.Zona,
  fp.[Número Guía],
  fp.NotaControlCalidad,
  fp.NotaGeneralControlCalidad,
  fp.CajasEquivalentes,
  fp.[Peso Neto Envase Operacional],
  fp.Origen,
  fp.[Tipo Proceso],
  fp.[Calibre Equivalente],
  fp.[Nombre Grupo Productores],
  fp.[Codigo Grupo Productores],
  fp.[Turno Trabajo],
  fp.Inicio,
  fp.Termino,
  fp.A;