SELECT
  TOP (100) PERCENT CI.DESCRIPCION,
  CONVERT(
    FLOAT,
    SUM(CAST(CD.DESCRIPCION AS FLOAT)) / CONVERT(FLOAT, SUM(CTD.MUESTRA))
  ) AS PORCENTAJE,
  R.PLANILLA,
  R.LOTE,
  CI.ITEM,
  CASE
    WHEN CI.ITEM = 1 THEN 'Calidad'
    WHEN CI.ITEM = 2 THEN 'Condicion'
    WHEN CI.ITEM = 3 THEN 'Dist. Calibre'
    WHEN CI.ITEM = 4 THEN 'Dist. Color'
    WHEN CI.ITEM = 8 THEN 'Firmezas'
    ELSE '**'
  END AS tipo,
  CTD.PLANILLA AS Planilla_Calidad,
  R.FECHA_RPA,
  R.CANTIDAD,
  R.TOTAL_KILOS,
  R.COD_PRE,
  P.NOM_PRO,
  CTD.NOTA,
  CTD.CUMPLENORMA,
  CTD.OBSERVACION,
  CTD.OBS_TOT_EXP,
  CTD.Velocidad,
  CTD.PeriodoFinal,
  CTD.NotaCalidad,
  R.TIPOFRU,
  tr.PATENTE,
  R.GUIA,
  CTD.TIT_PULPA,
  CTD.MUESTRA,
  CTD.FCH_INSPECCION,
  R.COD_ESP,
  R.COD_VAR,
  esp.NOM_ESP,
  R.COD_PRO,
  var.NOM_VAR,
  (
    SELECT
      SUM(rd.CANT_ENV_CONT) AS Expr1
    FROM
      Erpfrusys.dbo.RECEPACK_DET AS rd
    WHERE
      rd.COD_TEM = R.COD_TEM
      AND rd.COD_EMP = R.COD_EMP
      AND rd.PLANILLA = R.PLANILLA
  ) AS totes_sp
FROM
  Erpfrusys.dbo.RECEPACK AS R
  RIGHT JOIN Erpfrusys.dbo.PRODUCTORES AS P ON R.COD_EMP = P.COD_EMP
  AND R.COD_TEM = P.COD_TEM
  AND R.COD_PRO = P.COD_PRO
  LEFT JOIN Erpfrusys.dbo.CTRL_TIT_DATOS AS CTD ON R.COD_EMP = CTD.COD_EMP
  AND R.COD_TEM = CTD.COD_TEM
  AND R.ZON = CTD.ZON
  AND R.PLANILLA = CTD.PLANILLA_REC
  AND R.LOTE = CTD.LOTE
  LEFT JOIN Erpfrusys.dbo.CTRL_DATOS AS CD ON CTD.COD_EMP = CD.COD_EMP
  AND CTD.COD_TEM = CD.COD_TEM
  AND CTD.ZON = CD.ZON
  AND CTD.TIPO = CD.TIPO
  AND CTD.PLANILLA = CD.PLANILLA
  AND CTD.PLANILLA_REC = CD.PLANILLA_REC
  LEFT JOIN Erpfrusys.dbo.CTRL_ITEM AS CI ON CI.COD_EMP = CD.COD_EMP
  AND CI.COD_TEM = CD.COD_TEM
  AND CI.TIPO = CD.TIPO
  AND CI.COD_ITEM = CD.COD_ITEM
  AND CI.COD_FAMILIA = CD.COD_FAMILIA
  LEFT JOIN Erpfrusys.dbo.TIT_RECEPACK AS tr ON tr.COD_EMP = R.COD_EMP
  AND tr.COD_TEM = R.COD_TEM
  AND R.PLANILLA = tr.PLANILLA
  LEFT JOIN Erpfrusys.dbo.ESPECIE AS esp ON esp.COD_EMP = R.COD_EMP
  AND esp.COD_TEM = R.COD_TEM
  AND R.COD_ESP = esp.COD_ESP
  LEFT JOIN Erpfrusys.dbo.VARIEDAD AS var ON var.COD_EMP = R.COD_EMP
  AND var.COD_TEM = R.COD_TEM
  AND R.COD_VAR = var.COD_VAR
WHERE
  R.COD_EMP = 'MER'
  AND R.COD_TEM = '7'
  AND R.TIPOFRU = 'E'
  AND CTD.TIPO = 'R'
GROUP BY
  CI.DESCRIPCION,
  R.PLANILLA,
  R.LOTE,
  CI.ITEM,
  CTD.PLANILLA,
  R.FECHA_RPA,
  R.CANTIDAD,
  R.TOTAL_KILOS,
  R.COD_PRE,
  P.NOM_PRO,
  CTD.NOTA,
  CTD.CUMPLENORMA,
  CTD.OBSERVACION,
  CTD.OBS_TOT_EXP,
  CTD.Velocidad,
  CTD.PeriodoFinal,
  CTD.NotaCalidad,
  R.TIPOFRU,
  tr.PATENTE,
  R.GUIA,
  CTD.TIT_PULPA,
  CTD.MUESTRA,
  CTD.FCH_INSPECCION,
  R.COD_ESP,
  R.COD_VAR,
  esp.NOM_ESP,
  R.COD_PRO,
  var.NOM_VAR,
  R.COD_EMP,
  R.COD_TEM
ORDER BY
  R.LOTE;