CREATE VIEW dbo.v_sdp_com_prov WITH VIEW_METADATA AS
SELECT
  pi.COD_TEM AS 'TEMPORADA',
  pi.COD_CUA AS 'CUARTEL',
  p.COD_PRE AS 'CSG',
  pi.COD_INSCRIPCION AS 'SDP',
  pr.DESCRIPCION AS 'PROVINCIA',
  c.DESCRIPCION AS 'COMUNA',
  pi.COD_MER AS 'MERCADO'
FROM
  Erpfrusys.dbo.PREDIOS_INSPECCION pi
  LEFT OUTER JOIN Erpfrusys.dbo.PREDIOS p ON pi.COD_TEM = p.COD_TEM
  AND pi.COD_PRE = p.COD_PRE
  LEFT OUTER JOIN Erpfrusys.dbo.PROVINCIAS pr ON pr.COD_TEM = pi.COD_TEM
  AND pr.COD_PROVC = p.COD_PROVC
  LEFT OUTER JOIN Erpfrusys.dbo.COMUNAS c ON pi.COD_TEM = c.COD_TEM
  AND c.COD_COM = p.COD_COM
WHERE
  pi.COD_EMP = 'MER'
  AND pi.COD_TEM IN (5, 6)