SELECT
  p1.lote AS FOLIO,
  p1.CAJAS * a.KILOS AS KILOS_TOTALES,
  p.lote AS LOTE,
  p.PLANILLA AS PROCESO,
  r.NotaCalidad AS SEGREGACION
FROM
  ERPFRUSYS.dbo.PROCEPACK AS p
  LEFT JOIN ERPFRUSYS.dbo.RECEPACK AS r ON p.COD_EMP = r.COD_EMP
  AND p.COD_TEM = r.COD_TEM
  AND p.LOTE = r.LOTE
  AND p.TIPOFRU = 'E'
  LEFT JOIN ERPFRUSYS.dbo.PROPACKMIX AS p1 ON p1.PROCESO = p.PLANILLA
  AND p.COD_TEM = p1.COD_TEM
  AND p.COD_EMP = p1.COD_EMP
  LEFT JOIN ERPFRUSYS.dbo.AJUSTE AS a ON p1.COD_EMP = a.COD_EMP
  AND p1.COD_TEM = a.COD_TEM
  AND p1.ZON = a.ZON
  AND p1.proceso = a.PLANILLA
  AND p1.COD_ESP = a.COD_ESP
  AND p1.COD_ENV = a.COD_ENV
  AND p1.COD_EMB = a.COD_EMB
  LEFT JOIN ERPFRUSYS.dbo.ENVASEOPERACIONAL AS E ON p1.COD_TEM = E.COD_TEM
  AND p1.COD_EMP = E.COD_EMP
  AND p1.COD_ESP = E.COD_ESP
  AND p1.COD_ENVOP = E.COD_ENVOP
  AND p1.COD_EMB = E.COD_EMB
  AND p1.COD_ENV = E.COD_ENV
WHERE
  p.COD_ESP = 5
  AND p.COD_TEM = 6
  AND p.TIPOFRU = 'E'
  AND p1.COD_EXP = 64;