SELECT
  P.NOM_PACK,
  CAST(T.PLANILLA AS NVARCHAR(10)) AS PLANILLA,
  T.COD_TEM,
  T.COD_EMP,
  T.COD_PACK,
  T.COD_PRO,
  T.FECHA_RECEPCION,
  T.GUIA,
  T.CHOFER,
  T.PATENTE,
  T.HORA_RECEP,
  T.ZON,
  T.COD_PRE,
  T.COD_CUA,
  T.GLOSA,
  PR.NOM_PRO,
  CU.DESCRIPCION AS DESC_CUARTEL,
  PRE.DESCRIPCION,
  DET.LOTE,
  DET.COD_ENV,
  DET.CANTIDAD,
  CAST(DET.KILOS_BINS AS FLOAT) AS KILOS_BINS,
  DET.ORDEN_ING,
  DET.TOTAL_KILOS,
  DET.CANT_ENV_CONT,
  E.NOM_ESP,
  V.NOM_VAR,
  F.NOM_FRI,
  ED.COD_ENV_CONT,
  ISNULL(DET.TIPOFRU, R.TIPOFRU) AS TIPOFRU,
  R.TOTAL_KILOS_CAMION,
  R.KILOS_NETO_CAMION,
  Erpfrusys.dbo.EXPORTADORES.NOM_EXP,
  V.COD_VAR
FROM
  Erpfrusys.dbo.TIT_RECEPACK AS T
  JOIN Erpfrusys.dbo.RECEPACK AS R ON R.COD_EMP = T.COD_EMP
  AND R.COD_TEM = T.COD_TEM
  AND R.ZON = T.ZON
  AND R.PLANILLA = T.PLANILLA
  LEFT JOIN Erpfrusys.dbo.RECEPACK_DET AS DET ON DET.COD_EMP = R.COD_EMP
  AND DET.COD_TEM = R.COD_TEM
  AND DET.ZON = R.ZON
  AND DET.PLANILLA = R.PLANILLA
  AND DET.LOTE = R.LOTE
  JOIN Erpfrusys.dbo.PACKINGS AS P ON T.COD_EMP = P.COD_EMP
  AND T.COD_TEM = P.COD_TEM
  AND T.COD_PACK = P.COD_PACK
  JOIN Erpfrusys.dbo.PRODUCTORES AS PR ON PR.COD_EMP = T.COD_EMP
  AND PR.COD_TEM = T.COD_TEM
  AND PR.COD_PRO = T.COD_PRO
  JOIN Erpfrusys.dbo.PREDIOS AS PRE ON PRE.COD_EMP = T.COD_EMP
  AND PRE.COD_TEM = T.COD_TEM
  AND PRE.COD_PRO = T.COD_PRO
  AND PRE.COD_PRE = T.COD_PRE
  JOIN Erpfrusys.dbo.CUARTELES AS CU ON CU.COD_EMP = T.COD_EMP
  AND CU.COD_TEM = T.COD_TEM
  AND CU.COD_PRO = T.COD_PRO
  AND CU.COD_PRE = T.COD_PRE
  AND CU.COD_CUA = T.COD_CUA
  JOIN Erpfrusys.dbo.FRIOS AS F ON T.COD_EMP = F.COD_EMP
  AND T.COD_TEM = F.COD_TEM
  AND T.COD_FRI = F.COD_FRI
  JOIN Erpfrusys.dbo.ESPECIE AS E ON E.COD_EMP = R.COD_EMP
  AND E.COD_TEM = R.COD_TEM
  AND E.COD_ESP = R.COD_ESP
  JOIN Erpfrusys.dbo.VARIEDAD AS V ON V.COD_EMP = R.COD_EMP
  AND V.COD_TEM = R.COD_TEM
  AND V.COD_ESP = R.COD_ESP
  AND V.COD_VAR = R.COD_VAR
  JOIN Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR ON PR.COD_EMP = Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR.COD_EMP
  AND PR.COD_TEM = Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR.COD_TEM
  AND PR.COD_PRO = Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR.COD_PRO
  JOIN Erpfrusys.dbo.EXPORTADORES ON Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR.COD_EXP = Erpfrusys.dbo.EXPORTADORES.COD_EXP
  AND Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR.COD_TEM = Erpfrusys.dbo.EXPORTADORES.COD_TEM
  AND Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR.COD_EMP = Erpfrusys.dbo.EXPORTADORES.COD_EMP
  LEFT JOIN Erpfrusys.dbo.ENVASE AS EN ON EN.COD_EMP = DET.COD_EMP
  AND EN.COD_TEM = DET.COD_TEM
  AND EN.COD_ENV = DET.COD_ENV
  LEFT JOIN Erpfrusys.dbo.ENVASE_DETALLE AS ED ON ED.COD_EMP = EN.COD_EMP
  AND ED.COD_TEM = EN.COD_TEM
  AND ED.COD_ENV = EN.COD_ENV;