SELECT
  R.COD_TIPO_FRIO AS [Tipo Frio],
  TIT.COD_EMP AS Empresa,
  TIT.COD_TEM AS Temporada,
  TIT.PLANILLA AS [Nº Guia de Recepcion],
  CAST(
    CONVERT(NVARCHAR(20), TIT.FECHA_RECEPCION, 103) AS SMALLDATETIME
  ) AS FechaRecepcion,
  TIT.FECHA_COSECHA AS [Fecha Cosecha],
  TIT.ZON AS Zona,
  R.COD_PACK AS CodigoPacking,
  R.COD_PRO AS CodigoProductor,
  R.COD_FRI AS CodigoFrio,
  R.COD_ESP AS CodigoEspecie,
  R.COD_VAR AS CodigoVariedad,
  R.LOTE AS NumeroLote,
  R.COD_ENV AS CodigoEnvase,
  R.CANTIDAD,
  R.KILOS AS KilosPromedio,
  R.TOTAL_KILOS AS TotalKilos,
  T.DESCRIPCION AS NombreTemporada,
  EM.NOM_EMP AS NombreEmpresa,
  P.NOM_PRO AS NombreProductor,
  F.NOM_FRI AS NombreFrio,
  PK.NOM_PACK AS NombrePacking,
  E.NOM_ESP AS NombreEspecie,
  ISNULL(
    (
      SELECT
        VARIEDAD.NOM_VAR
      FROM
        Erpfrusys.dbo.VARIEDAD
      WHERE
        VARIEDAD.COD_EMP = R.COD_EMP
        AND VARIEDAD.COD_TEM = R.COD_TEM
        AND VARIEDAD.COD_ESP = R.COD_ESP
        AND VARIEDAD.COD_VAR = R.COD_VAR
    ),
    N''
  ) AS NombreVariedad,
  Z.NOM_ZON AS NombreZona,
  CASE
    R.TIPOFRU
    WHEN 'E' THEN 'Exportación'
    WHEN 'C' THEN 'Comercial'
    WHEN 'P' THEN 'Preprocesada'
    WHEN 'D' THEN 'Desverdisada'
  END AS TipoFruta,
  TIT.GUIA AS [Guía de Recepción Productor (SII)],
  ISNULL(CP.NOM_CALIDAD, N'Sin Calidad') AS [Calidad Packing],
  GP.DESCRIPCION AS [Nombre Grupo Productores],
  GP.COD_GRP_PRO AS [Codigo Grupo Productores],
  TIT.CHOFER AS [Nombre Conductor],
  TIT.PATENTE,
  TIT.HORA_RECEP AS [Hora Recepcion],
  PRE.COD_GRP_PRE AS [Codigo Grupo Huerto],
  GH.DESCRIPCION AS [Nombre Grupo Huerto],
  TIT.COD_PRE AS [Codigo Predio],
  PRE.DESCRIPCION AS [Nombre Predio],
  TIT.COD_CUA AS [Codigo Cuartel],
  CUA.DESCRIPCION AS [Nombre Cuartel],
  CASE
    WHEN EXISTS (
      SELECT
        1
      FROM
        Erpfrusys.dbo.TIT_CTACTE_ENVASES AS CC
      WHERE
        CC.COD_EMP = TIT.COD_EMP
        AND CC.COD_TEM = TIT.COD_TEM
        AND CC.ZON = TIT.ZON
        AND CC.PLANILLA_PK = TIT.PLANILLA
    ) THEN 'Asignado a Cta.Cte. Envases'
    ELSE 'No asignado a Cta.Cte. Envases'
  END AS [Asignado a Cta.Cte. Envases],
  TIT.GLOSA AS Observaciones,
  R.COD_TIPO_TRA AS [Codigo Tipo Tratamiento],
  TT.DESCRIPCION AS [Tipo Tratamiento],
  CASE
    TIT.TIPO_REC
    WHEN 'N' THEN 'Normal'
    ELSE 'Traslado'
  END AS [Tipo Recepcion],
  CASE
    WHEN TIT.SW_COMPRA = 1 THEN 'Compra Kilo'
    WHEN TIT.EXEDENTE = 1 THEN 'Exedente'
    WHEN TIT.SW_PREFRIO = 1 THEN 'Fruta ya Enfriada'
    ELSE 'Sin Estatus'
  END AS [Estatus Recepcion],
  ISNULL(QC.NombreArchivo, N'') AS NombreArchivo,
  PX.COD_EXP AS [Cod Exportadora],
  EX.NOM_EXP AS [Nom Exportadora],
  ISNULL(R.COD_GRADO_MADUREZ, N'') AS [Codigo Grado Madurez],
  ISNULL(MAD.DESCRIPCION, N'') AS [Grado Madurez],
  ISNULL(R.NotaCalidad, N'') AS [Nota Segregacion],
  ISNULL(R.Velocidad, N'') AS [Velocidad Proceso],
  ISNULL(CONVERT(INT, xt.BIN_MOS), 0) AS NO_CUMPLE_MOSAICO,
  TIT.FECHA_RECEPCION AS fecha_digitacion,
  xt.BIN_MOS,
  CTRL_TIT_DATOS.OBS_TOT_EXP,
  CTRL_TIT_DATOS.PLANILLA,
  CTRL_TIT_DATOS.PLANILLA_REC,
  QC.Planilla_QC,
  QC.PLANILLA_REC AS Expr1,
  RECEPACK_DET.ORDEN_ING
FROM
  Erpfrusys.dbo.TIT_RECEPACK AS TIT
  JOIN Erpfrusys.dbo.RECEPACK AS R ON TIT.COD_TEM = R.COD_TEM
  AND TIT.COD_EMP = R.COD_EMP
  AND TIT.ZON = R.ZON
  AND TIT.PLANILLA = R.PLANILLA
  JOIN Erpfrusys.dbo.TEMPORADAS AS T ON TIT.COD_TEM = T.COD_TEM
  AND TIT.COD_EMP = T.COD_EMP
  JOIN Erpfrusys.dbo.EMPRESAS AS EM ON T.COD_EMP = EM.COD_EMP
  JOIN Erpfrusys.dbo.PRODUCTORES AS P ON R.COD_TEM = P.COD_TEM
  AND R.COD_EMP = P.COD_EMP
  AND R.COD_PRO = P.COD_PRO
  JOIN Erpfrusys.dbo.FRIOS AS F ON R.COD_TEM = F.COD_TEM
  AND R.COD_EMP = F.COD_EMP
  AND R.COD_FRI = F.COD_FRI
  JOIN Erpfrusys.dbo.PACKINGS AS PK ON TIT.COD_TEM = PK.COD_TEM
  AND TIT.COD_EMP = PK.COD_EMP
  AND TIT.COD_PACK = PK.COD_PACK
  JOIN Erpfrusys.dbo.ESPECIE AS E ON R.COD_TEM = E.COD_TEM
  AND R.COD_EMP = E.COD_EMP
  AND R.COD_ESP = E.COD_ESP
  LEFT JOIN Erpfrusys.dbo.RECEPACK_QC AS QC ON QC.COD_EMP = R.COD_EMP
  AND QC.COD_TEM = R.COD_TEM
  AND QC.ZON = R.ZON
  AND QC.PLANILLA_REC = R.PLANILLA
  AND QC.LOTE = R.LOTE
  JOIN Erpfrusys.dbo.ZONAS AS Z ON TIT.COD_EMP = Z.COD_EMP
  AND TIT.COD_TEM = Z.COD_TEM
  AND TIT.ZON = Z.ZON
  LEFT JOIN Erpfrusys.dbo.CTRL_TIT_DATOS ON TIT.PLANILLA = CTRL_TIT_DATOS.PLANILLA
  AND TIT.COD_TEM = CTRL_TIT_DATOS.COD_TEM
  AND TIT.COD_EMP = CTRL_TIT_DATOS.COD_EMP
  LEFT JOIN Erpfrusys.dbo.CALIDADPACKING AS CP ON R.COD_EMP = CP.COD_EMP
  AND R.COD_TEM = CP.COD_TEM
  AND R.COD_ESP = CP.COD_ESP
  AND R.COD_CALIDAD = CP.COD_CALIDAD
  LEFT JOIN Erpfrusys.dbo.GRUPOSPRODUCTORES AS GP ON GP.COD_EMP = P.COD_EMP
  AND GP.COD_TEM = P.COD_TEM
  AND GP.COD_GRP_PRO = P.COD_GRP_PRO
  LEFT JOIN Erpfrusys.dbo.PREDIOS AS PRE ON TIT.COD_EMP = PRE.COD_EMP
  AND TIT.COD_TEM = PRE.COD_TEM
  AND TIT.COD_PRO = PRE.COD_PRO
  AND TIT.COD_PRE = PRE.COD_PRE
  LEFT JOIN Erpfrusys.dbo.GRUPOSPREDIOS AS GH ON PRE.COD_EMP = GH.COD_EMP
  AND PRE.COD_TEM = GH.COD_TEM
  AND PRE.COD_GRP_PRE = GH.COD_GRP_PRE
  LEFT JOIN Erpfrusys.dbo.CUARTELES AS CUA ON TIT.COD_EMP = CUA.COD_EMP
  AND TIT.COD_TEM = CUA.COD_TEM
  AND TIT.COD_PRO = CUA.COD_PRO
  AND TIT.COD_PRE = CUA.COD_PRE
  AND TIT.COD_CUA = CUA.COD_CUA
  LEFT JOIN Erpfrusys.dbo.TIPO_TRATAMIENTO AS TT ON R.COD_EMP = TT.COD_EMP
  AND R.COD_TEM = TT.COD_TEM
  AND R.COD_ESP = TT.COD_ESP
  AND R.COD_TIPO_TRA = TT.COD_TIPO_TRA
  LEFT JOIN Erpfrusys.dbo.PRODUCTOR_X_EXPORTADOR AS PX ON PX.COD_EMP = P.COD_EMP
  AND PX.COD_TEM = P.COD_TEM
  AND PX.COD_PRO = P.COD_PRO
  LEFT JOIN Erpfrusys.dbo.EXPORTADORES AS EX ON EX.COD_EMP = PX.COD_EMP
  AND EX.COD_TEM = PX.COD_TEM
  AND EX.COD_EXP = PX.COD_EXP
  LEFT JOIN Erpfrusys.dbo.GRADO_MADUREZ AS MAD ON R.COD_EMP = MAD.COD_EMP
  AND R.COD_TEM = MAD.COD_TEM
  AND R.COD_GRADO_MADUREZ = MAD.COD_GRADO_MADUREZ
  LEFT JOIN recepcion.dbo.TIT_RECEPACK AS xt ON TIT.COD_TEM = xt.COD_TEM
  AND TIT.COD_EMP = xt.COD_EMP
  AND TIT.PLANILLA = xt.PLANILLA
  JOIN Erpfrusys.dbo.RECEPACK_DET ON RECEPACK_DET.PLANILLA = TIT.PLANILLA
  AND RECEPACK_DET.COD_TEM = TIT.COD_TEM
  AND RECEPACK_DET.COD_EMP = TIT.COD_EMP
  AND RECEPACK_DET.ZON = TIT.ZON;