[req]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn
req_extensions = v3_req

[dn]
CN=192.168.7.26
C=MX
ST=Estado
L=Ciudad
O=Validacion App Development
OU=IT Department

[v3_req]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names

[alt_names]
IP.1 = 192.168.7.26
DNS.1 = 192.168.7.26
DNS.2 = localhost
DNS.3 = validacion.local